// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vggnbwtblbxvytteaoip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZ25id3RibGJ4dnl0dGVhb2lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTExMjEsImV4cCI6MjA2Mjk4NzEyMX0.mS1Umyl6N1vZjxXKqlkwJQlFoarWBN36ttTb6p3kJHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});